[package]
name = "my_uuid_folder"
version = "0.1.0"
edition = "2024"

[lib]
# Windows がロード可能な C 言語互換の DLL を出力する指定
crate-type = ["cdylib"]


[dependencies]
windows-core = "0.58" # これがマクロの動作に必須です
windows = { version = "0.58", features = [
    "implement",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_SystemServices",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }