# File: inspect_lunr_index.py
# This script reads the lunr_index.js file generated by generate_lunr_index.py,
# extracts the serialized Lunr index data, and displays details about the index.
# It prints out each term along with the number of documents in which the term appears.

import re
import json

def extract_index_data(js_filename):
    """
    Extract JSON data from a JavaScript file that defines prebuiltIndexData.
    Assumes the file contains a line like:
      var prebuiltIndexData = { ... };
    """
    with open(js_filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Use regex to extract the JSON part.
    # This regex assumes that the variable is defined on one line, but uses DOTALL to match multiline JSON.
    match = re.search(r'var\s+prebuiltIndexData\s*=\s*(\{.*?\});', content, re.DOTALL)
    if not match:
        raise ValueError("Could not find prebuiltIndexData in the file.")
    
    json_str = match.group(1).strip()
    return json.loads(json_str)

def display_term_statistics(index_data):
    """
    Display each term in the inverted index along with the count of document postings.
    This function expects the invertedIndex to be either:
      - A dictionary mapping terms to posting lists, or
      - A list of [term, postings] pairs.
    """
    inverted_index = index_data.get("invertedIndex", None)
    if inverted_index is None:
        print("No invertedIndex found in the index data.")
        return

    print("Indexed Terms and Document Occurrence Counts:")
    print("----------------------------------------------")

    # Handle case when inverted_index is a list of [term, postings] pairs.
    if isinstance(inverted_index, list):
        # Sort by term (first element of each pair)
        for item in sorted(inverted_index, key=lambda x: x[0] if isinstance(x, list) and len(x) >= 2 else ""):
            if isinstance(item, list) and len(item) >= 2:
                term = item[0]
                postings = item[1]
                count = len(postings) if isinstance(postings, list) else 0
                print(f"{term}: {count}")
            else:
                print(f"Unexpected item format: {item}")
    # Fallback: handle case when inverted_index is a dict.
    elif isinstance(inverted_index, dict):
        for term, postings in sorted(inverted_index.items()):
            count = len(postings) if isinstance(postings, list) else 0
            print(f"{term}: {count}")
    else:
        print("Unexpected type for invertedIndex:", type(inverted_index))

def main():
    js_filename = "lunr_index.js"
    try:
        index_data = extract_index_data(js_filename)
    except Exception as e:
        print(f"Error reading index data: {e}")
        return

    # Print basic index details
    print("Index Details:")
    version = index_data.get("version", "unknown")
    fields = index_data.get("fields", [])
    ref_field = index_data.get("ref", "unknown")
    print(f"  Version: {version}")
    print(f"  Indexed Fields: {fields}")
    print(f"  Reference Field: {ref_field}\n")
    
    # Display term-level statistics
    display_term_statistics(index_data)

if __name__ == "__main__":
    main()
