[project]
name = "llama-cpp-sse"
version = "0.1.18"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-cpuinfo>=9.0.0",
]

[project.scripts]
check-env = "llama_cpp_sse.check_env:main"
check-sse = "llama_cpp_sse.check_sse:main"
cleanup-gpu = "llama_cpp_sse.cleanup_gpu:main"
benchmark = "llama_cpp_sse.benchmark:main"
download-bin = "llama_cpp_sse.download_bin:main"
download-models = "llama_cpp_sse.download_models:main"
test-model = "llama_cpp_sse.test_model:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
