[project]
name = "mdns-inspector"
version = "0.1.28"
description = "mDNS capture and forward tool prototype"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Takashi Sasaki" }
]
dependencies = [
    "platformdirs>=4.9.2",
]

[project.urls]
Homepage = "https://x.com/TakashiSasaki"

[project.scripts]
mdns-inspector = "my_mdns.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/my_mdns"]
